import puppeteer from "puppeteer-core";
const OUT="/private/tmp/claude-501/-Users-yasufumi--work-EbisSoft/8d462af0-1d44-4e7e-9101-1d0c2e43fb47/scratchpad";
const b = await puppeteer.launch({executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",headless:"new",args:["--no-sandbox"]});
const p = await b.newPage();
await p.setViewport({width:1280,height:900,deviceScaleFactor:2});
await p.goto("http://localhost:4173/EbisSoft/",{waitUntil:"networkidle0"});
await new Promise(r=>setTimeout(r,4800));
await p.screenshot({path:`${OUT}/hint.png`, clip:{x:880,y:600,width:400,height:300}});
await p.click(".assistant-launcher");
await p.waitForSelector(".assistant-panel input");
await p.type(".assistant-panel input","組み込み開発もできますか？");
await p.click('.assistant-panel button[type="submit"]');
await new Promise(r=>setTimeout(r,3000));
await (await p.$(".assistant-slot")).screenshot({path:`${OUT}/panel.png`});
await b.close();
